//! # tpt-script — the Pythonic scripting layer of the TPT stack
//!
//! A `.tpt` file is ordinary Rust with a script-shaped ergonomics layer:
//!
//! ```
//! use tpt_script::prelude::*;
//!
//! let t = table_of(vec![
//!     f64s("x", vec![-1.0, 2.0, 3.0]),
//!     strs("grp", &["a", "b", "a"]),
//! ]);
//!
//! script! {
//!     let pos = t.filter("x", ">", 0.0);
//!     let by_grp = pos.groupby(&["grp"]).agg(&[("x", "mean"), ("*", "count")]);
//!     print by_grp.show();
//! }
//! assert_eq!(pos.len(), 2);
//! assert_eq!(by_grp.len(), 2);
//! ```
//!
//! ## What is real here
//!
//! * [`prelude`] — one glob import for the whole stack with Pythonic names
//!   (`read`, `write`, `omni`, `stat`, `viz`, `sym`, ...).
//! * [`table::TableExt`] — real chaining on [`tpt_omni::Table`]: `.filter()`,
//!   `.groupby().agg()`, `.plot()` (a genuine [`tpt_viz::Plot`]), `.ols()`.
//! * [`script!`] — a `macro_rules!` block of Pythonic statements that expands
//!   to those calls, and [`script_main!`] which wraps a body in a `main` that
//!   prints a traceback and exits non-zero on failure.
//! * [`run`] / [`run_script`] — panic ("exception") capture with a
//!   Python-style traceback.
//!
//! ## Implicit error handling
//!
//! In script mode failures *raise* instead of returning `Result`: chaining
//! methods panic with a [`ScriptError`], and [`run`] converts that panic into
//! `Err(ScriptError)` with the panic location. So a script never writes `?`,
//! while library code can use the `try_*` twins (`try_filter`, `try_agg`,
//! `try_col_f64`, ...) and `?` with [`Res`].
//!
//! ## Scoped down (honest limits)
//!
//! * [`run_script`] does **not** compile Rust. The real `tpt script` binary
//!   generates `fn main` and calls `rustc`; here `run_script` executes a tiny
//!   documented statement language (`let` / `print` / `assert` / `panic` over
//!   f64 arithmetic) inside `catch_unwind`. See [`runner`].
//! * `.groupby()` keys are compared by their rendered string form; groups are
//!   emitted in lexicographic key order. Aggregations are `mean`, `sum`,
//!   `count`, `min`, `max`, `std`.
//! * `.plot()` produces a scatter of the first two numeric columns only.

pub mod error;
pub mod prelude;
pub mod runner;
pub mod table;

pub use error::{Res, ScriptError};
pub use runner::{capture, run, run_script, run_script_err};
pub use table::{f64s, i64s, strs, table_of, Grouped, TableExt, Value};

// The stack, under Pythonic module names.
pub use tpt_io as io;
pub use tpt_omni as omni;
pub use tpt_stat as stat;
pub use tpt_sym as sym;
pub use tpt_viz as viz;

/// A block of Pythonic statements that expands to plain `tpt_*` calls.
///
/// Supported statement forms (each terminated by `;`):
///
/// ```text
/// let name = expr;        let mut name = expr;
/// print expr;             // println!("{}", expr)
/// expr;                   // evaluated, result discarded
/// ```
///
/// The block imports [`crate::prelude`] and expands *in place*, so bindings
/// stay visible to the surrounding code.
///
/// ```
/// use tpt_script::prelude::*;
/// let t = table_of(vec![f64s("v", vec![1.0, 5.0])]);
/// script! {
///     let big = t.filter("v", ">", 2.0);
///     print big.len();
/// }
/// assert_eq!(big.len(), 1);
/// ```
#[macro_export]
macro_rules! script {
    ($($body:tt)*) => {
        #[allow(unused_imports)]
        use $crate::prelude::*;
        $crate::script_stmt!($($body)*);
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! script_stmt {
    () => {};
    (let mut $n:ident = $e:expr; $($rest:tt)*) => {
        let mut $n = $e;
        $crate::script_stmt!($($rest)*);
    };
    (let $n:ident = $e:expr; $($rest:tt)*) => {
        let $n = $e;
        $crate::script_stmt!($($rest)*);
    };
    (print $e:expr; $($rest:tt)*) => {
        println!("{}", $e);
        $crate::script_stmt!($($rest)*);
    };
    ($e:expr; $($rest:tt)*) => {
        let _ = $e;
        $crate::script_stmt!($($rest)*);
    };
}

/// Generate the `main` of a `.tpt`-style file: runs a [`script!`] body under
/// [`run`], prints a traceback to stderr and exits `1` if it raises.
///
/// ```
/// mod my_script {
///     tpt_script::script_main! {
///         let xs = tpt_script::table_of(vec![tpt_script::f64s("v", vec![1.0, 2.0])]);
///         print xs.show();
///     }
/// }
/// my_script::main();
/// ```
#[macro_export]
macro_rules! script_main {
    ($($body:tt)*) => {
        /// Entry point generated by `tpt_script::script_main!`.
        pub fn main() {
            let outcome = $crate::run(|| {
                $crate::script! { $($body)* }
                Ok(())
            });
            if let Err(e) = outcome {
                eprintln!("{}", e.traceback());
                ::std::process::exit(1);
            }
        }
    };
}
