//! Procedural macros for [`tpt-grad`](https://docs.rs/tpt-grad):
//! `#[derive_grad]`, `#[derive_vmap]` and `#[derive_jit]`.
//!
//! Each macro re-emits the annotated function unchanged and appends one
//! companion function, so the attributes are freely composable:
//!
//! ```ignore
//! #[derive_grad]
//! #[derive_vmap]
//! #[derive_jit]
//! fn f(x: Tensor<f64>, y: Tensor<f64>) -> Tensor<f64> { x.clone() * y.clone() }
//! // => f, f_grad, f_vmap, f_jit
//! ```
//!
//! The generated code refers to the runtime engine through `::tpt_grad`, so the
//! `tpt-grad` crate must be a dependency of the calling crate. The accepted
//! subset of Rust is documented in the `tpt-grad` crate docs and enforced in
//! `analyze.rs`.

mod analyze;

use analyze::{analyze, Fun, Kind};
use proc_macro::TokenStream;
use proc_macro2::TokenStream as TS;
use quote::{format_ident, quote};
use syn::{parse_macro_input, Error, ItemFn};

fn entry(attr: TokenStream, item: TokenStream, mac: &str, build: fn(&Fun) -> TS) -> TokenStream {
    let item = parse_macro_input!(item as ItemFn);
    if !attr.is_empty() {
        let e = Error::new(
            proc_macro2::Span::call_site(),
            format!("#[{mac}] takes no arguments"),
        )
        .to_compile_error();
        return quote!(#item #e).into();
    }
    let original = item.clone();
    match analyze(item, mac) {
        Ok(f) => {
            let kept = &f.item;
            let extra = build(&f);
            quote!(#kept #extra).into()
        }
        // Keep the original function so downstream call sites still resolve.
        Err(e) => {
            let e = e.to_compile_error();
            quote!(#original #e).into()
        }
    }
}

/// Generate `f_grad(args..) -> (Ret, Vec<Tensor<f64>>)`: the value of `f` plus
/// the gradient w.r.t. each `Tensor<f64>` argument, in declaration order.
///
/// The body is replayed on a runtime [`Tape`](../tpt_grad/struct.Tape.html), so
/// the gradients are exact reverse-mode derivatives.
#[proc_macro_attribute]
pub fn derive_grad(attr: TokenStream, item: TokenStream) -> TokenStream {
    entry(attr, item, "derive_grad", gen_grad)
}

/// Generate `f_vmap(args..) -> Tensor<f64>`: apply `f` to each sample along
/// dim 0 of every `Tensor<f64>` argument and stack the results along a new
/// dim 0. `f64` arguments are shared across the batch.
#[proc_macro_attribute]
pub fn derive_vmap(attr: TokenStream, item: TokenStream) -> TokenStream {
    entry(attr, item, "derive_vmap", gen_vmap)
}

/// Generate `f_jit(args..) -> Ret`, a **fusion hint**: for an element-wise body
/// the whole expression is evaluated in one pass with no intermediate tensors.
/// Bodies containing `.sum()`/`.mean()` fall back to calling `f` directly.
#[proc_macro_attribute]
pub fn derive_jit(attr: TokenStream, item: TokenStream) -> TokenStream {
    entry(attr, item, "derive_jit", gen_jit)
}

fn gen_grad(f: &Fun) -> TS {
    let it = &f.item;
    let vis = &it.vis;
    let name = &it.sig.ident;
    let gname = format_ident!("{}_grad", name);
    let inputs = &it.sig.inputs;
    let ret = &f.ret;
    let block = &it.block;
    let ts = f.tensor_args();
    let doc = format!(
        "Value and reverse-mode gradients of [`{name}`], one per tensor argument \
         (generated by `#[derive_grad]`)."
    );
    quote! {
        #[doc = #doc]
        #[allow(clippy::let_and_return, unused_parens)]
        #vis fn #gname(#inputs) -> (#ret, ::std::vec::Vec<::tpt_grad::__rt::Tensor<f64>>) {
            let __tape = ::tpt_grad::__rt::Tape::new();
            #( let #ts = __tape.var(#ts); )*
            let __out = #block;
            let __grads = __out.backward();
            (
                <#ret as ::tpt_grad::__rt::FromVar>::from_var(&__out),
                ::std::vec![ #( __grads.gradient(&#ts) ),* ],
            )
        }
    }
}

fn gen_vmap(f: &Fun) -> TS {
    let it = &f.item;
    let vis = &it.vis;
    let name = &it.sig.ident;
    let vname = format_ident!("{}_vmap", name);
    let inputs = &it.sig.inputs;
    let ts = f.tensor_args();
    if ts.is_empty() {
        return Error::new_spanned(
            &it.sig,
            "#[derive_vmap]: at least one `Tensor<f64>` argument is required",
        )
        .to_compile_error();
    }
    let lead = ts[0];
    let call: Vec<TS> = f
        .args
        .iter()
        .map(|a| {
            let id = &a.ident;
            match a.kind {
                Kind::Tensor => quote!(::tpt_grad::__rt::vmap::sample(&#id, __i)),
                Kind::Scalar => quote!(#id),
            }
        })
        .collect();
    let doc = format!(
        "Batched [`{name}`]: maps over dim 0 of every tensor argument and stacks \
         the results (generated by `#[derive_vmap]`)."
    );
    quote! {
        #[doc = #doc]
        #vis fn #vname(#inputs) -> ::tpt_grad::__rt::Tensor<f64> {
            let __n = ::tpt_grad::__rt::vmap::batch_len(&#lead);
            let mut __outs: ::std::vec::Vec<::tpt_grad::__rt::Tensor<f64>> =
                ::std::vec::Vec::with_capacity(__n);
            for __i in 0..__n {
                let __r = #name( #(#call),* );
                __outs.push(::tpt_grad::__rt::VmapOut::into_sample(__r));
            }
            ::tpt_grad::__rt::vmap::stack0(__outs)
        }
    }
}

fn gen_jit(f: &Fun) -> TS {
    let it = &f.item;
    let vis = &it.vis;
    let name = &it.sig.ident;
    let jname = format_ident!("{}_jit", name);
    let inputs = &it.sig.inputs;
    let ret = &f.ret;
    let block = &it.block;
    let ts = f.tensor_args();
    let args: Vec<&syn::Ident> = f.args.iter().map(|a| &a.ident).collect();
    let fusable = f.elementwise && f.ret_is_tensor && !ts.is_empty();
    let doc = format!(
        "Fused single-pass [`{name}`] (generated by `#[derive_jit]`). {}",
        if fusable {
            "The body is lowered to one element-wise kernel; no intermediate tensors are allocated."
        } else {
            "This body is not element-wise, so the fusion hint falls back to calling the original function."
        }
    );
    if !fusable {
        return quote! {
            #[doc = #doc]
            #vis fn #jname(#inputs) -> #ret { #name(#(#args),*) }
        };
    }
    let idx: Vec<usize> = (0..ts.len()).collect();
    quote! {
        #[doc = #doc]
        #[allow(clippy::let_and_return, unused_parens)]
        #vis fn #jname(#inputs) -> #ret {
            ::tpt_grad::__rt::jit::fuse(
                &[ #(&#ts),* ],
                move |__e: &[f64]| -> f64 {
                    #( let #ts: f64 = __e[#idx]; )*
                    #block
                },
            )
        }
    }
}
