[package]
name = "tpt-for-abstract-interp"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"
authors = ["TPT Solutions"]
description = "Generic abstract-interpretation framework."

readme = "README.md"
keywords = ["abstract-interpretation", "static-analysis", "verification", "semantics", "analysis"]
categories = ["science", "mathematics", "development-tools::debugging"]

[dependencies]

[lints]
rust = { unsafe_op_in_unsafe_fn = "warn" }
clippy = { all = "warn" }

[[example]]
name = "abstract_interp_basic"
path = "examples/interval_analysis.rs"

